Repository Bentheburrito/sacastats, pull requests merged in 2022-06, with the labels that each got.

#82 Got rid of bootstrap map warning
  priv/static/css/bootstrap-override.css
Labels: bug

#83 Mobile Selection Styles
  priv/static/css/flex-bootstrap-table-selection.css
Labels: bug, styling/css

#90 Alpha site pass
  lib/sacastats_web/templates/layout/root.html.heex
  lib/sacastats_web/templates/page/index.html.heex
  priv/static/css/index.css
  priv/static/css/styles.css
Labels: improvement, styling/css

#92 Weapon Table Clean up
  priv/static/css/bootstrap-override.css
  priv/static/js/character/weapons-table.js
  priv/static/js/flex-bootstrap-table-column.js
  priv/static/js/flex-bootstrap-table-selection.js
  priv/static/js/flex-bootstrap-table.js
Labels: improvement, styling/css

#86 Character cleanup
  lib/sacastats_web/controllers/character_controller.ex
  lib/sacastats_web/templates/character/general.html.heex
  lib/sacastats_web/templates/character/template.html.heex
  lib/sacastats_web/templates/character/weapons.html.heex
  lib/sacastats_web/templates/layout/root.html.heex
  priv/static/css/app.css
  priv/static/css/character/general.css
  priv/static/css/flex-bootstrap-table-selection.css
  priv/static/css/styles.css
  priv/static/images/character/icons/class/CombatMedic_Icon.png
  priv/static/images/character/icons/class/Engineer_Icon.png
  priv/static/images/character/icons/class/HeavyAssault_Icon.png
  priv/static/images/character/icons/class/Infiltrator_Icon.png
  priv/static/images/character/icons/class/LightAssault_Icon.png
  priv/static/images/character/icons/class/MAX_Icon.png
  priv/static/images/character/icons/sex/female.png
  priv/static/images/character/icons/sex/male.png
  priv/static/images/character/icons/sex/robot.png
  priv/static/js/character/model.js
Labels: improvement, styling/css

#96 Update image defaults
  lib/sacastats/scripts/get_weapons.exs
  lib/sacastats/static_data/weapons.json
Labels: improvement

#88 Character General Alpha stats
  lib/sacastats/census_cache/fallbacks.ex
  lib/sacastats/schemas/session.ex
  lib/sacastats_web/controllers/character_controller.ex
  lib/sacastats_web/templates/character/general.html.heex
  lib/sacastats_web/templates/character/template.html.heex
  priv/static/css/character/general.css
  priv/static/css/styles.css
  priv/static/js/formats.js
Labels: improvement, styling/css

#98 Initial view fix
  lib/sacastats_web/controllers/outfit_controller.ex
  lib/sacastats_web/live/poll_live/view.ex
  lib/sacastats_web/router.ex
  lib/sacastats_web/templates/character/general.html.heex
  lib/sacastats_web/templates/character/sessions.html.heex
  lib/sacastats_web/templates/character/template.html.heex
  lib/sacastats_web/templates/character/weapons.html.heex
  lib/sacastats_web/templates/layout/root.html.heex
  lib/sacastats_web/templates/outfit/poll_lookup.html.heex
  lib/sacastats_web/templates/page/index.html.heex
  lib/sacastats_web/views/outfit_view.ex
  priv/static/css/app.css
  priv/static/css/index.css
  priv/static/css/navbar-events.css
  priv/static/css/outfit/poll-lookup.css
  priv/static/css/styles.css
  priv/static/images/outfit/plus-sign-light.png
  priv/static/images/outfit/plus-sign.png
  priv/static/js/flex-bootstrap-table-column.js
  priv/static/js/flex-bootstrap-table-filter.js
  priv/static/js/flex-bootstrap-table-selection.js
  priv/static/js/flex-bootstrap-table.js
  priv/static/js/outfit/poll-lookup.js
Labels: bug, improvement

#93 Revisited Outfit Polls
  lib/sacastats/application.ex
  lib/sacastats/schemas/poll.ex
  lib/sacastats/schemas/poll/item.ex
  lib/sacastats/schemas/poll/item/choice.ex
  lib/sacastats/schemas/poll/item/vote.ex
  lib/sacastats/schemas/poll_tem/multi_choice.ex
  lib/sacastats/schemas/poll_tem/text.ex
  lib/sacastats_web/discord_auth.ex
  lib/sacastats_web/live/poll_live.ex
  lib/sacastats_web/live/poll_live/create.ex
  lib/sacastats_web/live/poll_live/results.ex
  lib/sacastats_web/live/poll_live/view.ex
  lib/sacastats_web/router.ex
  lib/sacastats_web/templates/layout/app.html.heex
  lib/sacastats_web/templates/layout/live.html.heex
  lib/sacastats_web/templates/layout/root.html.heex
  lib/sacastats_web/templates/poll/create.html.heex
  lib/sacastats_web/templates/poll/results.html.heex
  lib/sacastats_web/templates/poll/view.html.heex
  lib/sacastats_web/views/poll_view.ex
  priv/repo/migrations/20220226221040_add_poll_schemas.exs
  priv/repo/migrations/20220319213132_update_poll.exs
Labels: enhancement, improvement

#102 MAX should always be capitalized
  priv/static/js/character/model.js
Labels: bug

#100 Fully hiding "Copied!" toast
  lib/sacastats_web/templates/character/weapons.html.heex
  priv/static/js/flex-bootstrap-table-selection.js
Labels: bug, styling/css

#105 Clean Model loading
  priv/static/js/character/model.js
Labels: bug, styling/css

#109 Update Poll Copy Link Text
  lib/sacastats_web/live/poll_live/create.ex
Labels: bug

#116 Fixed Filter NPE
  priv/static/js/flex-bootstrap-table-filter.js
Labels: bug

#114 Mobile nav background fix
  assets/css/character/template.css
  lib/sacastats_web/templates/character/template.html.heex
  priv/static/css/character/template.css
  priv/static/css/flex-bootstrap-table-selection.css
  priv/static/css/index.css
  priv/static/css/navbar-events.css
  priv/static/js/navbar-events.js
Labels: bug, styling/css, mobile
