Repository Bentheburrito/sacastats, pull requests merged in 2022-02, with the labels that each got.

#33 Universal Character page header
  lib/sacastats_web/controllers/page_controller.ex
  lib/sacastats_web/templates/character/general.html.heex
  lib/sacastats_web/templates/character/template.html.heex
  priv/static/css/character/template.css
Labels: enhancement

#32 Weapon stats layout initialization
  lib/sacastats_web/templates/character/weapons.html.heex
  priv/static/css/character/weapons.css
  priv/static/css/styles.css
  priv/static/js/character/weapons.js
  priv/static/js/scripts.js
Labels: enhancement

#30 Centered the character name and id on mobile
  lib/sacastats_web/templates/character/template.html.heex
  priv/static/css/character/general.css
  priv/static/css/character/template.css
Labels: bug

#36 Weapon stats
  lib/sacastats_web/controllers/character_controller.ex
  lib/sacastats_web/templates/character/general.html.heex
  lib/sacastats_web/templates/character/lookup.html.heex
  lib/sacastats_web/templates/character/weapons.html.heex
  lib/sacastats_web/templates/layout/app.html.heex
  priv/static/css/character/weapons.css
  priv/static/css/styles.css
  priv/static/images/character/alphaAurax.png
  priv/static/js/character/lookup.js
  priv/static/js/character/weapons-table.js
  priv/static/js/character/weapons.js
  priv/static/js/flex-bootstrap-table.js
  priv/static/js/formats.js
  priv/static/js/loading-screen.js
  priv/static/js/navbar-events.js
  priv/static/js/scripts.js
  priv/static/js/scroll-to-top.js
  priv/static/js/subpages.js
Labels: enhancement

#38 Update :planetside_api to v3
  config/runtime.exs
  lib/sacastats.ex
  lib/sacastats/application.ex
  lib/sacastats/event_handler.ex
  lib/sacastats/scripts/get_xp.exs
  lib/sacastats/session_tracker.ex
  lib/sacastats_web/controllers/character_controller.ex
  mix.exs
  mix.lock
Labels: improvement

#39 Fixed search sort issue.
  priv/static/js/flex-bootstrap-table.js
Labels: bug

#41 GitHub Actions/CI
  .github/workflows/test_and_lint.yml
  config/config.exs
  config/runtime.exs
  lib/sacastats.ex
  lib/sacastats/application.ex
  lib/sacastats/event_handler.ex
  lib/sacastats/mailer.ex
  lib/sacastats/schemas/character_session.ex
  lib/sacastats/scripts/get_vehicles.exs
  lib/sacastats/scripts/get_weapons.exs
  lib/sacastats/scripts/get_xp.exs
  lib/sacastats/session_tracker.ex
  lib/sacastats/utils/static_data.ex
  lib/sacastats_web/controllers/character_controller.ex
  lib/sacastats_web/discord_auth.ex
  lib/sacastats_web/endpoint.ex
  lib/sacastats_web/plugs/assign_current_user.ex
  lib/sacastats_web/telemetry.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20211126012108_character_sessions.exs
  test/support/channel_case.ex
  test/support/conn_case.ex
  test/support/data_case.ex
Labels: documentation, improvement, test

#40 Static weapon image info, filter excessive double quotes, and display item image on character's weapon page
  lib/sacastats/scripts/get_weapons.exs
  lib/sacastats/static_data/weapons.json
  lib/sacastats/utils/static_data.ex
  lib/sacastats_web/templates/character/weapons.html.heex
  lib/sacastats_web/templates/layout/app.html.heex
  priv/static/js/scripts.js
Labels: enhancement, improvement
