Repository Bentheburrito/sacastats, pull requests merged in 2022-10, with the labels that each got.

#130 Removed NPE
  priv/static/js/flex-bootstrap-table-filter.js
Labels: bug

#131 Fix set next aurax visibilities
  lib/sacastats_web/templates/character/weapons.html.heex
  priv/static/js/character/weapons.js
  priv/static/js/flex-bootstrap-table-filter.js
  priv/static/js/flex-bootstrap-table.js
Labels: bug

#127 Convert Session Page to a LIveView
  config/config.exs
  lib/sacastats.ex
  lib/sacastats/census_cache.ex
  lib/sacastats/census_cache/fallbacks.ex
  lib/sacastats/event_tracker.ex
  lib/sacastats/event_tracker/deduper.ex
  lib/sacastats/schemas/session.ex
  lib/sacastats/sids.ex
  lib/sacastats_web/controllers/character_controller.ex
  lib/sacastats_web/live/poll_live/results.ex
  lib/sacastats_web/live/poll_live/view.ex
  lib/sacastats_web/live/session_live/view.ex
  lib/sacastats_web/router.ex
  lib/sacastats_web/templates/character/session.html.heex
  lib/sacastats_web/templates/character/sessions.html.heex
  lib/sacastats_web/views/character_view.ex
  mix.lock
  test/sacastats/event_tracker/deduper_test.exs
  test/sacastats_web/controllers/page_controller_test.exs
Labels: improvement

#122 Main Functionality and Fixes for Outfit Polls v2
  lib/sacastats/schemas/poll.ex
  lib/sacastats/schemas/poll/item.ex
  lib/sacastats/schemas/poll/item/choice.ex
  lib/sacastats/schemas/poll/item/vote.ex
  lib/sacastats_web/live/poll_live.ex
  lib/sacastats_web/live/poll_live/create.ex
  lib/sacastats_web/live/poll_live/manage.ex
  lib/sacastats_web/live/poll_live/results.ex
  lib/sacastats_web/live/poll_live/view.ex
  lib/sacastats_web/router.ex
  lib/sacastats_web/templates/poll/create.html.heex
  lib/sacastats_web/templates/poll/manage.html.heex
  lib/sacastats_web/templates/poll/results.html.heex
  lib/sacastats_web/templates/poll/view.html.heex
  lib/sacastats_web/views/poll_view.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20220715123344_add_optional_field_poll_item.exs
  priv/repo/migrations/20220718235334_add_visible_results_to_poll_item.exs
  priv/repo/migrations/20220719234934_add_timestamps_to_poll_schemas.exs
  priv/repo/migrations/20220722011642_add_poll_option_columns.exs
  priv/repo/migrations/20220723152506_cascade_delete_poll_items_votes_choices.exs
  priv/repo/migrations/20220723162757_add_unique_votes_constraint.exs
Labels: enhancement, improvement
