Repository Bentheburrito/sacastats, pull requests merged in 2022-07, with the labels that each got.

#112 Fix dateTime formatter
  priv/static/js/formats.js
Labels: bug

#117 New ESS Health Monitoring + Event Processing Strategy to Increase ESS Robustness
  config/test.exs
  lib/sacastats/application.ex
  lib/sacastats/census_cache/fallbacks.ex
  lib/sacastats/event_tracker.ex
  lib/sacastats/event_tracker/deduper.ex
  lib/sacastats/event_tracker/manager.ex
  lib/sacastats/event_tracker/report.ex
  lib/sacastats/event_tracker/supervisor.ex
  lib/sacastats/sids.ex
  lib/sacastats_web/controllers/page_controller.ex
  mix.lock
  test/sacastats/event_tracker/deduper_test.exs
  test/sacastats/event_tracker/report_test.exs
  test/test_helper.exs
Labels: enhancement

#120 Custom Discord OAuth2 Reimplementation
  lib/sacastats/schemas/discord_user.ex
  lib/sacastats/schemas/poll.ex
  lib/sacastats_web/controllers/page_controller.ex
  lib/sacastats_web/discord_auth.ex
  lib/sacastats_web/endpoint.ex
  lib/sacastats_web/live/poll_live.ex
  lib/sacastats_web/live/poll_live/view.ex
  lib/sacastats_web/templates/layout/root.html.heex
  lib/sacastats_web/templates/page/account.html.heex
  lib/sacastats_web/views/poll_view.ex
  mix.exs
  priv/repo/migrations/20220707024346_add_discord_user.exs
Labels: improvement

#121 Fix being unable to login when the discord user has no avatar
  lib/sacastats/schemas/discord_user.ex
Labels: bug
