Repository Bentheburrito/sacastats, pull requests merged in 2023-01, with the labels that each got.

#146 Favorite characters
  assets/src/character/lookup.ts
  assets/src/character/template.ts
  lib/sacastats.ex
  lib/sacastats/application.ex
  lib/sacastats/characters.ex
  lib/sacastats/event_tracker/deduper.ex
  lib/sacastats/schemas/census/character.ex
  lib/sacastats/schemas/census/online_status.ex
  lib/sacastats/schemas/character/favorite.ex
  lib/sacastats/world_tracker.ex
  lib/sacastats_web/controllers/character_controller.ex
  lib/sacastats_web/live/character_live/search.ex
  lib/sacastats_web/live/session_live/view.ex
  lib/sacastats_web/router.ex
  lib/sacastats_web/templates/character/general.html.heex
  lib/sacastats_web/templates/character/lookup.html.heex
  lib/sacastats_web/templates/character/template.html.heex
  lib/sacastats_web/templates/layout/app.html.heex
  lib/sacastats_web/templates/layout/live.html.heex
  lib/sacastats_web/templates/layout/root.html.heex
  mix.exs
  priv/repo/migrations/20220723211019_add_favorite_characters.exs
  priv/static/css/bootstrap-override.css
  priv/static/css/character/lookup.css
  priv/static/css/character/template.css
  priv/static/images/faction/NSO.png
Labels: enhancement, mobile

#152 Fix crash for "Snowman kill by squad member" xp
  lib/sacastats.ex
  lib/sacastats_web/views/character_view.ex
Labels: bug

#151 Fix error when visiting certain new(ish) characters
  lib/sacastats/characters.ex
  lib/sacastats/schemas/census/character.ex
Labels: bug

#147 Latest session
  lib/sacastats/schemas/session.ex
  lib/sacastats_web/controllers/character_controller.ex
  lib/sacastats_web/router.ex
Labels: enhancement

#156 Added progress bar headers for BR and Current certs
  lib/sacastats/characters.ex
  lib/sacastats_web/templates/character/general.html.heex
Labels: improvement

#155 Removed overflow for long character names
  lib/sacastats_web/templates/character/template.html.heex
  lib/sacastats_web/templates/layout/root.html.heex
  priv/static/css/character/template.css
  priv/static/css/navbar-events.css
Labels: bug, styling/css, mobile

#157 Add a TTL of 24h to entries in character_cache
  lib/sacastats/characters.ex
  lib/sacastats/schemas/census/online_status.ex
  lib/sacastats/world_tracker.ex
Labels: improvement

#159 Fix unformatted dates on LiveViews
  assets/js/app.js
  assets/src/formats.ts
  lib/sacastats_web/live/character_live/search.ex
  lib/sacastats_web/live/session_live/view.ex
  lib/sacastats_web/templates/character/general.html.heex
  lib/sacastats_web/templates/character/session.html.heex
  lib/sacastats_web/templates/character/template.html.heex
  lib/sacastats_web/views/character_view.ex
Labels: bug, code refactor

#161 Fix bug in prod
  lib/sacastats_web/live/character_live/search.ex
Labels: bug
